// <auto-generated />
using System;
using ClassHub.ClassHubContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassHub.ClassHubContext.Migrations
{
    [DbContext(typeof(ClassHubDbContext))]
    [Migration("20251029152916_CriacaoTurmaDB")]
    partial class CriacaoTurmaDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ClassHub.ClassHubContext.Models.AlunoTurma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DtMatricula")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdAluno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTurma")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdTurma");

                    b.HasIndex("IdAluno", "IdTurma")
                        .IsUnique();

                    b.ToTable("AlunoTurmas");
                });

            modelBuilder.Entity("ClassHub.ClassHubContext.Models.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DtFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdProfessor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdProfessor");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("ClassHub.ClassHubContext.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ClassHub.ClassHubContext.Models.AlunoTurma", b =>
                {
                    b.HasOne("ClassHub.ClassHubContext.Models.Usuario", "Aluno")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassHub.ClassHubContext.Models.Turma", "Turma")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdTurma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("ClassHub.ClassHubContext.Models.Turma", b =>
                {
                    b.HasOne("ClassHub.ClassHubContext.Models.Usuario", "Professor")
                        .WithMany("TurmasLecionadas")
                        .HasForeignKey("IdProfessor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("ClassHub.ClassHubContext.Models.Turma", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("ClassHub.ClassHubContext.Models.Usuario", b =>
                {
                    b.Navigation("Matriculas");

                    b.Navigation("TurmasLecionadas");
                });
#pragma warning restore 612, 618
        }
    }
}
